### ISSUE TITLE
Feature request: Calculate shipping cost (getDocumentPrice)

### ISSUE THREAD

**Issue by gianpaj** [eugene-manuilov/novaposhta#1]
https://devcenter.novaposhta.ua/blog/%D0%BF%D1%80%D0%BE%D1%81%D1%87%D0%B5%D1%82-%D1%81%D1%82%D0%BE%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D0%B8

https://devcenter.novaposhta.ua/docs/services/556eef34a0fe4f02049c664e/operations/55702ee2a0fe4f0cf4fc53ef

**Comment by holyCowMp3** [comment]
Requested feature was added in new version. Check version of your library.

**Comment by gianpaj** [comment]
nice! thanks

**Comment by eugene-manuilov** [comment]
Thanks @markFieldman, but it hasn't been released yet. I am working on a new release that will include more changes. Stay tuned.

**Comment by eugene-manuilov** [comment]
Ok, it's published now. Thanks @gianpaj and @markFieldman!
