### ISSUE TITLE
getCounterpartyContactPerson error method

### ISSUE THREAD

**Issue by yapizza** [eugene-manuilov/novaposhta#5]
getCounterpartyContactPerson not methods in nova poshta.)))
"calledMethod": "getCounterpartyContactPersons" correct
https://devcenter.novaposhta.ua/docs/services/557eb8c8a0fe4f02fc455b2d/operations/557fe424a0fe4f105c087612

**Comment by eugene-manuilov** [comment]
Hi @yapizza 

thanks for your help! I have fixed it and published a new version. Please, update your dependency and it should be fixed.
